blueprint:
  name: Korekta temperatury TRV
  description: Korekta temperatury na podstawie zewnetrznego sensora
  domain: automation
  input:
    glowica_trv:
      name: Glowica TRV
      description: Wybierz encje glowicy TRV
      selector:
        entity:
          domain: climate
    zewnetrzny_sensor_temperatury:
      name: Zewnetrzny sensor temperatury
      description: Wybierz encje zewnetrznego sensora temperatury
      selector:
        entity:
          domain: sensor
    korekta_temperatury:
      name: Zmienna Korekta temperatury
      description: Wybierz encje zmiennej "Korekta temperatury"
      selector:
        entity:
          domain: number
trigger_variables:
  sensor_entity: !input zewnetrzny_sensor_temperatury
trigger:
  - platform: numeric_state
    entity_id: !input glowica_trv
    attribute: current_temperature
    above: "{{ states(sensor_entity) | float(0) + 0.2 }}"
  - platform: numeric_state
    entity_id: !input glowica_trv
    attribute: current_temperature
    below: "{{ states(sensor_entity) | float(0) - 0.2 }}"
condition: []
action:
  - variables:
      trv_entity: !input glowica_trv
      sensor_entity: !input zewnetrzny_sensor_temperatury
      correction_entity: !input korekta_temperatury
  - service: number.set_value
    target:
      entity_id: !input korekta_temperatury
    data:
      value: "{{ (states(korekta_temperatury) | float (0) + state_attr(trv_entity, 'current_temperature') - states(sensor_entity) | float(0) ) | round(1) }}"
mode: single
